baseURL: "https://shanu.me" 
title: Shanu Venkatesan
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Experience
          url: experience/
          weight: 5 
        - name: Education
          url: education/
          weight: 2

params:
    description: "This website hosts Shanu Venkatesan's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Shanu Venkatesan
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["education","experience"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Shanu Venkatesan
          subtitle: "I am a Graduate student at NYU (Management of Technology) with strong experience in data analytics, forecasting, and strategy execution. Previously worked as a Market Analyst, where I improved profit margins by 20% and helped drive a 45% revenue increase using SQL, Excel, Tableau, and predictive analysis. Skilled in Python, R, SQL, Tableau, Power BI, and data modeling. Worked on ML projects including an Intrusion Detection System and large-scale data transformation pipelines."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Education
              url: education/
            - name: Experience
              url: experience/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:contact@shanu.me
        - name: GitHub
          url: https://github.com/ShanuVenkatesan
        - name: LinkedIn
          url: https://www.linkedin.com/in/shanu-venkatesan-analyst/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Shanu Venkatesan"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2